# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ dev, gitaction_stage1]
  pull_request:
    branches: [ dev, master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install torch==2.2.0 --break-system-packages --index-url https://download.pytorch.org/whl/cpu
        python -m pip install .
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with nose2 and pytest
      run: |
        nose2 -s ./tests
        pytest ./tests/unit

